### ISSUE TITLE
query data upon action instead of up-front

### ISSUE THREAD

**Issue by itsbrandondev** [hgraph-io/hedera-revenue-dashboard#36]
when using the application, we should query the data upon action (dropdown change, checkbox checked etc) instead of querying all the information upfront

**Comment by tmctl** [comment]
@itsbrandondev why?

**Comment by tmctl** [comment]
we're still loading all the data in one front end call, though doing it in a backend to leverage caching

**Comment by tmctl** [comment]
solution here - https://github.com/hgraph-io/hedera-revenue-dashboard/pull/102
